apiVersion: integration/v1
kind: Trigger
name: sysdig-trigger-alert-created
version: 1
summary: alert-created
description: |
  This trigger fires when a Sysdig alert is created

responders:
- webhook

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#

build:
  apiVersion: build/v1
  kind: Docker

publish:
  repository: relaysh/sysdig-trigger-alert-created
