apiVersion: integration/v1
kind: Integration
name: sysdig
channel: stable
version: v20200514
summary: Sysdig Integration
license: Apache-2.0
homepage: https://github.com/relay-integrations/relay-sysdig
source: https://github.com/relay-integrations/relay-sysdig

description: |
  This integration provides various points to interact with Sysdig, either via triggers or workflow steps.

owner:
  name: Puppet, Inc.
  email: relay@puppet.com
  url: https://puppet.com

tags:
- incident response
- rto
