apiVersion: integration/v1
kind: Step
name: alert-disable
version: 1
summary: Disable alert
description: Disable a Sysdig alert.
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/sysdig-step-alert-disable
schemas:
  spec:
    source: file
    file: spec.schema.json
examples:
- summary: Disable an alert 
  content: 
    apiVersion: v1
    kind: Step
    name: disable-alert
    image: relaysh/sysdig-step-alert-disable
    spec:
      alertName: !Parameter alertName
      sysdig:
        connection:
          token: !Secret sysdigToken
