apiVersion: integration/v1
kind: Step
name: alert-enable
version: 1
summary: Enable alert
description: |
  This step can enable a Sysdig alert.
build:
  apiVersion: build/v1
  kind: Docker
publish:
  repository: relaysh/sysdig-step-alert-enable
schemas:
  spec:
    source: file
    file: spec.schema.json
examples:
- summary: Enable an alert 
  content: 
    apiVersion: v1
    kind: Step
    name: enable-alert
    image: relaysh/sysdig-step-alert-enable
    spec:
      alertName: !Parameter alertName
      sysdig:
        connection:
          token: !Secret sysdigToken
